---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-autoscaler
  labels:
    app: cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      containers:
        - image: taimir93/cluster-autoscaler:v0.1
          name: cluster-autoscaler
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --v=4
            - --cloud-provider=openstack-heat
            - --cloud-config=heat-config.ini
            - --nodes=1:10:tiny_cluster:autoscale:cluster_size
          env:
            - name: OS_REGION_NAME
              value: RegionOne
          imagePullPolicy: "Always"
