heat_template_version: 2016-10-14

description: Template defines a k8s minion.

parameters:
  # network params
  private_network:
    type: string
  private_subnet:
    type: string
  public_network:
    type: string
  secgroup_autoscale:
    type: string
  # provisioning and general config
  install_minion:
    type: string
  kube_master_eth0:
    type: string
  image:
    type: string
  flavor:
    type: string
  key:
    type: string


resources:
  server_name_post_fix:
    type: OS::Heat::RandomString
    properties:
      length: 4

  kube_minion:
    type: OS::Nova::Server
    properties:
      image: {get_param: image}
      flavor: {get_param: flavor}
      key_name: {get_param: key}
      name:
        list_join: [-, [node, {get_resource: server_name_post_fix}]]
      personality: {"/home/k8s/heat-config.ini": {get_file: "https://raw.githubusercontent.com/taimir/kube-openstack/master/heat-config.ini"}}
      user_data_format: RAW
      user_data: {get_param: install_minion}
      networks:
        - port: {get_resource: kube_minion_eth0}

  kube_minion_eth0:
    type: OS::Neutron::Port
    properties:
      network: {get_param: private_network}
      security_groups:
        - {get_param: secgroup_autoscale}
      fixed_ips:
        - subnet: {get_param: private_subnet}

  kube_minion_floating:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: {get_param: public_network}
      port_id: {get_resource: kube_minion_eth0}
